name: Manual Build

on:
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'yarn'

      - name: Install dependencies
        run: |
          echo "Yarn: $(yarn --version || echo 'yarn not found')"
          # Try a strict install for Yarn v2+/berry, fallback to a normal install
          yarn install --immutable --inline-builds || yarn install

      - name: Build (Vite)
        env:
          # Supply Vite client env vars from repository secrets (set these in repo Settings → Secrets → Actions)
          VITE_APP_MAPTILER_ACCESS_TOKEN: ${{ secrets.VITE_APP_MAPTILER_ACCESS_TOKEN }}
          VITE_APP_GOOGLE_MAPS_API_KEY: ${{ secrets.VITE_APP_GOOGLE_MAPS_API_KEY }}
          VITE_APP_API_URL: ${{ secrets.VITE_APP_API_URL }}
          GENERATE_SOURCEMAP: 'false'
          VITE_APP_VERSION: v3.2.0
          
        run: |
          yarn build

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v4
        with:
          path: ./dist

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Configure Pages
        uses: actions/configure-pages@v3

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v1
